export const data = [
  {
    "Type": "RES",
    "St": "S",
    "Address": "47  Gold ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,961",
    "Year Built": 1825,
    "Total Rooms": 10,
    "Beds Total": 5,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.11,
    "Original List Price": "$129,900",
    "List Price": "$129,900",
    "Sale Price": "$117,000",
    "SPLP": "90.1%",
    "SP Sq Ft": "$59.66",
    "Contract Date": "10/23/2015",
    "DOM": 75
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "720  Linden ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,770",
    "Year Built": 1900,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$110,000",
    "List Price": "$82,500",
    "Sale Price": "$70,000",
    "SPLP": "84.8%",
    "SP Sq Ft": "$39.55",
    "Contract Date": "10/26/2015",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "27  Bly ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,374",
    "Year Built": 1900,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$110,027",
    "List Price": "$99,888",
    "Sale Price": "$107,000",
    "SPLP": "107.1%",
    "SP Sq Ft": "$77.87",
    "Contract Date": "12/7/2015",
    "DOM": 82
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "62  Lansdale ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,466",
    "Year Built": 1920,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.08,
    "Original List Price": "$139,900",
    "List Price": "$139,900",
    "Sale Price": "$135,000",
    "SPLP": "96.5%",
    "SP Sq Ft": "$92.09",
    "Contract Date": "12/9/2015",
    "DOM": 8
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "317  Caroline ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,059",
    "Year Built": 1900,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.05,
    "Original List Price": "$72,900",
    "List Price": "$74,900",
    "Sale Price": "$70,500",
    "SPLP": "94.1%",
    "SP Sq Ft": "$66.57",
    "Contract Date": "12/11/2015",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "165  Milburn ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,290",
    "Year Built": 1870,
    "Total Rooms": 6,
    "Beds Total": 2,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.11,
    "Original List Price": "$139,900",
    "List Price": "$139,900",
    "Sale Price": "$135,000",
    "SPLP": "96.5%",
    "SP Sq Ft": "$104.65",
    "Contract Date": "1/1/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "238  Henrietta ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,194",
    "Year Built": 1910,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.07,
    "Original List Price": "$119,000",
    "List Price": "$119,000",
    "Sale Price": "$119,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$99.66",
    "Contract Date": "1/3/2016",
    "DOM": 31
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "15  Whitmore ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Bungalow, Cape Cod",
    "Sq Ft Total": "1,358",
    "Year Built": 1900,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.08,
    "Original List Price": "$49,900",
    "List Price": "$49,900",
    "Sale Price": "$53,000",
    "SPLP": "106.2%",
    "SP Sq Ft": "$39.03",
    "Contract Date": "1/3/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "30  Raymond ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "1,350",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$134,900",
    "List Price": "$134,900",
    "Sale Price": "$130,000",
    "SPLP": "96.4%",
    "SP Sq Ft": "$96.30",
    "Contract Date": "1/10/2016",
    "DOM": 48
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "263  Benton ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "1,384",
    "Year Built": 1890,
    "Total Rooms": 6,
    "Beds Total": 2,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.08,
    "Original List Price": "$92,500",
    "List Price": "$92,500",
    "Sale Price": "$85,000",
    "SPLP": "91.9%",
    "SP Sq Ft": "$61.42",
    "Contract Date": "1/21/2016",
    "DOM": 30
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "100  Southview TER",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,400",
    "Year Built": 1934,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.1,
    "Original List Price": "$129,900",
    "List Price": "$129,900",
    "Sale Price": "$128,000",
    "SPLP": "98.5%",
    "SP Sq Ft": "$91.43",
    "Contract Date": "1/22/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "12  Raymond ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,344",
    "Year Built": 1900,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.08,
    "Original List Price": "$129,900",
    "List Price": "$129,900",
    "Sale Price": "$121,000",
    "SPLP": "93.1%",
    "SP Sq Ft": "$90.03",
    "Contract Date": "1/30/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "31  Wilmington ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,462",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.1,
    "Original List Price": "$99,500",
    "List Price": "$99,500",
    "Sale Price": "$108,500",
    "SPLP": "109.0%",
    "SP Sq Ft": "$74.21",
    "Contract Date": "2/4/2016",
    "DOM": 7
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "37  Wilmer ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial, Historic",
    "Sq Ft Total": "2,193",
    "Year Built": 1910,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 2.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.11,
    "Original List Price": "$174,900",
    "List Price": "$174,900",
    "Sale Price": "$65,000",
    "SPLP": "37.2%",
    "SP Sq Ft": "$29.64",
    "Contract Date": "2/4/2016",
    "DOM": 29
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "544  Caroline ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,000",
    "Year Built": 1890,
    "Total Rooms": 5,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.05,
    "Original List Price": "$99,900",
    "List Price": "$99,900",
    "Sale Price": "$94,000",
    "SPLP": "94.1%",
    "SP Sq Ft": "$94.00",
    "Contract Date": "2/7/2016",
    "DOM": 14
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "205  Richard ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,674",
    "Year Built": 1885,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 1,
    "Numof Garage Spaces": 3,
    "Numof Acres": 0.09,
    "Original List Price": "$115,000",
    "List Price": "$115,000",
    "Sale Price": "$105,000",
    "SPLP": "91.3%",
    "SP Sq Ft": "$62.72",
    "Contract Date": "2/10/2016",
    "DOM": 62
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "523  Meigs ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial, Victorian",
    "Sq Ft Total": "2,630",
    "Year Built": 1900,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 2,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.1,
    "Original List Price": "$129,900",
    "List Price": "$119,900",
    "Sale Price": "$110,000",
    "SPLP": "91.7%",
    "SP Sq Ft": "$41.83",
    "Contract Date": "2/15/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "28  Lawton ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "2,107",
    "Year Built": 1890,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.06,
    "Original List Price": "$134,900",
    "List Price": "$129,900",
    "Sale Price": "$126,500",
    "SPLP": "97.4%",
    "SP Sq Ft": "$60.04",
    "Contract Date": "2/17/2016",
    "DOM": 37
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "5  Regent ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "1,155",
    "Year Built": 1910,
    "Total Rooms": 6,
    "Beds Total": 6,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.07,
    "Original List Price": "$88,900",
    "List Price": "$88,900",
    "Sale Price": "$94,000",
    "SPLP": "105.7%",
    "SP Sq Ft": "$81.39",
    "Contract Date": "2/20/2016",
    "DOM": 65
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "121  Cimarron DR",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Ranch",
    "Sq Ft Total": "1,130",
    "Year Built": 1952,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.16,
    "Original List Price": "$99,900",
    "List Price": "$91,900",
    "Sale Price": "$88,000",
    "SPLP": "95.8%",
    "SP Sq Ft": "$77.88",
    "Contract Date": "2/27/2016",
    "DOM": 47
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "675  Linden ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,396",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$73,000",
    "List Price": "$73,000",
    "Sale Price": "$73,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$52.29",
    "Contract Date": "3/2/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "69  Redfern DR",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,462",
    "Year Built": 1950,
    "Total Rooms": 7,
    "Beds Total": 4,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.12,
    "Original List Price": "$80,000",
    "List Price": "$80,000",
    "Sale Price": "$85,600",
    "SPLP": "107.0%",
    "SP Sq Ft": "$58.55",
    "Contract Date": "3/4/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "23  Sycamore ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,289",
    "Year Built": 1980,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.43,
    "Original List Price": "$154,900",
    "List Price": "$129,900",
    "Sale Price": "$127,000",
    "SPLP": "97.8%",
    "SP Sq Ft": "$98.53",
    "Contract Date": "3/6/2016",
    "DOM": 62
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "95  Beaufort ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,003",
    "Year Built": 1900,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$119,900",
    "List Price": "$119,900",
    "Sale Price": "$115,000",
    "SPLP": "95.9%",
    "SP Sq Ft": "$114.66",
    "Contract Date": "3/7/2016",
    "DOM": 14
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "22  Beaufort ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Victorian",
    "Sq Ft Total": "1,426",
    "Year Built": 1900,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.08,
    "Original List Price": "$119,900",
    "List Price": "$119,900",
    "Sale Price": "$128,000",
    "SPLP": "106.8%",
    "SP Sq Ft": "$89.76",
    "Contract Date": "3/13/2016",
    "DOM": 2
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "23  Lansdale ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,830",
    "Year Built": 1911,
    "Total Rooms": 9,
    "Beds Total": 4,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.09,
    "Original List Price": "$109,900",
    "List Price": "$109,900",
    "Sale Price": "$109,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$60.05",
    "Contract Date": "3/16/2016",
    "DOM": 6
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "517  Averill AVE",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,794",
    "Year Built": 1880,
    "Total Rooms": 9,
    "Beds Total": 5,
    "Baths Total": 2,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.08,
    "Original List Price": "$129,900",
    "List Price": "$129,900",
    "Sale Price": "$129,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$72.41",
    "Contract Date": "3/20/2016",
    "DOM": 15
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "115  Westview Ter",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,032",
    "Year Built": 1937,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 2.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.09,
    "Original List Price": "$123,500",
    "List Price": "$123,500",
    "Sale Price": "$125,000",
    "SPLP": "101.2%",
    "SP Sq Ft": "$121.12",
    "Contract Date": "3/22/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "531  Caroline ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,215",
    "Year Built": 1850,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.07,
    "Original List Price": "$124,900",
    "List Price": "$124,900",
    "Sale Price": "$124,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$102.80",
    "Contract Date": "3/22/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "420  Gregory ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Bungalow",
    "Sq Ft Total": "1,220",
    "Year Built": 1830,
    "Total Rooms": 6,
    "Beds Total": 2,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.11,
    "Original List Price": "$89,900",
    "List Price": "$89,900",
    "Sale Price": "$83,000",
    "SPLP": "92.3%",
    "SP Sq Ft": "$68.03",
    "Contract Date": "3/29/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "21  Pembroke ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,207",
    "Year Built": 1935,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.07,
    "Original List Price": "$109,900",
    "List Price": "$109,900",
    "Sale Price": "$109,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$91.05",
    "Contract Date": "4/4/2016",
    "DOM": 11
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "162  Seager ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod, Colonial",
    "Sq Ft Total": "1,246",
    "Year Built": 1890,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.06,
    "Original List Price": "$89,999",
    "List Price": "$89,999",
    "Sale Price": "$85,000",
    "SPLP": "94.4%",
    "SP Sq Ft": "$68.22",
    "Contract Date": "4/4/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "39  Fort Hill TER",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod, Colonial",
    "Sq Ft Total": "1,100",
    "Year Built": 1917,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.2,
    "Original List Price": "$134,900",
    "List Price": "$134,900",
    "Sale Price": "$134,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$122.64",
    "Contract Date": "4/5/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "525  Benton ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,975",
    "Year Built": 1905,
    "Total Rooms": 9,
    "Beds Total": 5,
    "Baths Total": 2,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.08,
    "Original List Price": "$135,000",
    "List Price": "$135,000",
    "Sale Price": "$138,000",
    "SPLP": "102.2%",
    "SP Sq Ft": "$69.87",
    "Contract Date": "4/14/2016",
    "DOM": 13
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "129  Cimarron DR",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Ranch",
    "Sq Ft Total": "1,378",
    "Year Built": 1951,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.16,
    "Original List Price": "$84,900",
    "List Price": "$84,900",
    "Sale Price": "$92,000",
    "SPLP": "108.4%",
    "SP Sq Ft": "$66.76",
    "Contract Date": "4/18/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "66  Bond ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,316",
    "Year Built": 1880,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.12,
    "Original List Price": "$119,900",
    "List Price": "$119,900",
    "Sale Price": "$119,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$91.11",
    "Contract Date": "4/19/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "25  Gold ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,503",
    "Year Built": 1920,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.11,
    "Original List Price": "$129,900",
    "List Price": "$119,900",
    "Sale Price": "$119,000",
    "SPLP": "99.2%",
    "SP Sq Ft": "$79.17",
    "Contract Date": "4/19/2016",
    "DOM": 64
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "93  Wilmington ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,470",
    "Year Built": 1920,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.1,
    "Original List Price": "$84,500",
    "List Price": "$84,500",
    "Sale Price": "$84,500",
    "SPLP": "100.0%",
    "SP Sq Ft": "$57.48",
    "Contract Date": "4/20/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "238  Laburnam CRES",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,536",
    "Year Built": 1900,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.15,
    "Original List Price": "$125,000",
    "List Price": "$125,000",
    "Sale Price": "$135,100",
    "SPLP": "108.1%",
    "SP Sq Ft": "$87.96",
    "Contract Date": "4/24/2016",
    "DOM": 2
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "16  Boothe ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,631",
    "Year Built": 1890,
    "Total Rooms": 8,
    "Beds Total": 5,
    "Baths Total": 2,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.28,
    "Original List Price": "$149,900",
    "List Price": "$149,900",
    "Sale Price": "$137,000",
    "SPLP": "91.4%",
    "SP Sq Ft": "$84.00",
    "Contract Date": "4/28/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "162  Edgemont RD",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,100",
    "Year Built": 1943,
    "Total Rooms": 5,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.12,
    "Original List Price": "$159,000",
    "List Price": "$140,000",
    "Sale Price": "$140,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$127.27",
    "Contract Date": "5/8/2016",
    "DOM": 16
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "76  Hickory ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "1,582",
    "Year Built": 1930,
    "Total Rooms": 7,
    "Beds Total": 4,
    "Baths Total": 2,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.11,
    "Original List Price": "$65,000",
    "List Price": "$75,000",
    "Sale Price": "$75,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$47.41",
    "Contract Date": "5/10/2016",
    "DOM": 144
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "16  Raymond ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,650",
    "Year Built": 1900,
    "Total Rooms": 9,
    "Beds Total": 4,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.07,
    "Original List Price": "$104,900",
    "List Price": "$104,900",
    "Sale Price": "$114,000",
    "SPLP": "108.7%",
    "SP Sq Ft": "$69.09",
    "Contract Date": "5/16/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "22  Lansdale ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,200",
    "Year Built": 1920,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.07,
    "Original List Price": "$119,900",
    "List Price": "$119,900",
    "Sale Price": "$125,000",
    "SPLP": "104.3%",
    "SP Sq Ft": "$104.17",
    "Contract Date": "5/20/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "30  Asbury ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,628",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 4,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.07,
    "Original List Price": "$129,900",
    "List Price": "$129,900",
    "Sale Price": "$129,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$79.79",
    "Contract Date": "5/23/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "621  Linden ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,792",
    "Year Built": 1900,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 1,
    "Numof Garage Spaces": 1.5,
    "Numof Acres": 0.08,
    "Original List Price": "$110,000",
    "List Price": "$98,000",
    "Sale Price": "$90,000",
    "SPLP": "91.8%",
    "SP Sq Ft": "$50.22",
    "Contract Date": "5/24/2016",
    "DOM": 39
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "713  Meigs ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod, Colonial",
    "Sq Ft Total": "1,586",
    "Year Built": 1900,
    "Total Rooms": 5,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.04,
    "Original List Price": "$84,900",
    "List Price": "$79,900",
    "Sale Price": "$55,000",
    "SPLP": "68.8%",
    "SP Sq Ft": "$34.68",
    "Contract Date": "6/1/2016",
    "DOM": 107
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "94  Gregory ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Bungalow, Ranch",
    "Sq Ft Total": "1,236",
    "Year Built": 1880,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.12,
    "Original List Price": "$129,900",
    "List Price": "$124,900",
    "Sale Price": "$126,000",
    "SPLP": "100.9%",
    "SP Sq Ft": "$101.94",
    "Contract Date": "6/12/2016",
    "DOM": 11
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "184  Richard ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,669",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.1,
    "Original List Price": "$99,900",
    "List Price": "$99,900",
    "Sale Price": "$99,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$59.86",
    "Contract Date": "6/12/2016",
    "DOM": 17
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "30  Fort Hill Ter",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,812",
    "Year Built": 1880,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.09,
    "Original List Price": "$139,900",
    "List Price": "$139,900",
    "Sale Price": "$135,500",
    "SPLP": "96.9%",
    "SP Sq Ft": "$74.78",
    "Contract Date": "6/16/2016",
    "DOM": 31
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "3  Sauer",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Bungalow",
    "Sq Ft Total": "1,028",
    "Year Built": 1890,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.09,
    "Original List Price": "$94,900",
    "List Price": "$94,900",
    "Sale Price": "$88,500",
    "SPLP": "93.3%",
    "SP Sq Ft": "$86.09",
    "Contract Date": "6/21/2016",
    "DOM": 14
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "67  Mount Vernon AVE",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,323",
    "Year Built": 1880,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.08,
    "Original List Price": "$84,900",
    "List Price": "$84,900",
    "Sale Price": "$75,000",
    "SPLP": "88.3%",
    "SP Sq Ft": "$56.69",
    "Contract Date": "6/22/2016",
    "DOM": 30
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "51  Seager ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial, Victorian",
    "Sq Ft Total": "1,287",
    "Year Built": 1890,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.1,
    "Original List Price": "$109,000",
    "List Price": "$109,000",
    "Sale Price": "$122,000",
    "SPLP": "111.9%",
    "SP Sq Ft": "$94.79",
    "Contract Date": "6/28/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "6  Regent ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,759",
    "Year Built": 1910,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.09,
    "Original List Price": "$164,900",
    "List Price": "$164,900",
    "Sale Price": "$140,000",
    "SPLP": "84.9%",
    "SP Sq Ft": "$79.59",
    "Contract Date": "7/17/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "20  Asbury ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "1,279",
    "Year Built": 1900,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$103,900",
    "List Price": "$103,900",
    "Sale Price": "$100,300",
    "SPLP": "96.5%",
    "SP Sq Ft": "$78.42",
    "Contract Date": "7/17/2016",
    "DOM": 5
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "66  Highland AVE",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,529",
    "Year Built": 1913,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 2.5,
    "Numof Acres": 0.21,
    "Original List Price": "$119,900",
    "List Price": "$119,900",
    "Sale Price": "$124,000",
    "SPLP": "103.4%",
    "SP Sq Ft": "$81.10",
    "Contract Date": "7/20/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "109  Hamilton ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "2,092",
    "Year Built": 1935,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.13,
    "Original List Price": "$112,900",
    "List Price": "$112,900",
    "Sale Price": "$113,000",
    "SPLP": "100.1%",
    "SP Sq Ft": "$54.02",
    "Contract Date": "7/27/2016",
    "DOM": 7
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "137  Henrietta ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Ranch",
    "Sq Ft Total": 774,
    "Year Built": 1900,
    "Total Rooms": 4,
    "Beds Total": 1,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.09,
    "Original List Price": "$55,000",
    "List Price": "$55,000",
    "Sale Price": "$55,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$71.06",
    "Contract Date": "8/1/2016",
    "DOM": 6
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "5  Blakeney Pl",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Bungalow, Colonial",
    "Sq Ft Total": "1,050",
    "Year Built": 1883,
    "Total Rooms": 7,
    "Beds Total": 2,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.06,
    "Original List Price": "$79,900",
    "List Price": "$79,900",
    "Sale Price": "$76,000",
    "SPLP": "95.1%",
    "SP Sq Ft": "$72.38",
    "Contract Date": "8/3/2016",
    "DOM": 70
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "493  Benton ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,492",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$124,900",
    "List Price": "$124,900",
    "Sale Price": "$130,000",
    "SPLP": "104.1%",
    "SP Sq Ft": "$87.13",
    "Contract Date": "8/7/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "35  Fort Hill Ter",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,440",
    "Year Built": 1940,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 2,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.09,
    "Original List Price": "$120,000",
    "List Price": "$120,000",
    "Sale Price": "$120,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$83.33",
    "Contract Date": "8/22/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "37  Lansdale ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,760",
    "Year Built": 1925,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 2.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.09,
    "Original List Price": "$139,900",
    "List Price": "$139,900",
    "Sale Price": "$139,900",
    "SPLP": "100.0%",
    "SP Sq Ft": "$79.49",
    "Contract Date": "8/31/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "23  Cimarron DR",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Ranch",
    "Sq Ft Total": 975,
    "Year Built": 1950,
    "Total Rooms": 4,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.21,
    "Original List Price": "$88,000",
    "List Price": "$88,000",
    "Sale Price": "$80,000",
    "SPLP": "90.9%",
    "SP Sq Ft": "$82.05",
    "Contract Date": "9/3/2016",
    "DOM": 17
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "88  Cimarron DR",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Ranch",
    "Sq Ft Total": "1,131",
    "Year Built": 1950,
    "Total Rooms": 5,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 1.5,
    "Numof Acres": 0.18,
    "Original List Price": "$109,000",
    "List Price": "$103,900",
    "Sale Price": "$96,000",
    "SPLP": "92.4%",
    "SP Sq Ft": "$84.88",
    "Contract Date": "9/9/2016",
    "DOM": 47
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "40  Sanford ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "1,582",
    "Year Built": 1900,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.09,
    "Original List Price": "$124,995",
    "List Price": "$124,995",
    "Sale Price": "$130,000",
    "SPLP": "104.0%",
    "SP Sq Ft": "$82.17",
    "Contract Date": "9/23/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "85  Southview",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,126",
    "Year Built": 1920,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.1,
    "Original List Price": "$127,500",
    "List Price": "$127,500",
    "Sale Price": "$122,000",
    "SPLP": "95.7%",
    "SP Sq Ft": "$108.35",
    "Contract Date": "10/3/2016",
    "DOM": 2
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "127  Redfern DR",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "2,193",
    "Year Built": 1910,
    "Total Rooms": 8,
    "Beds Total": 3,
    "Baths Total": 2.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.16,
    "Original List Price": "$69,000",
    "List Price": "$69,000",
    "Sale Price": "$70,000",
    "SPLP": "101.4%",
    "SP Sq Ft": "$31.92",
    "Contract Date": "10/3/2016",
    "DOM": 24
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "6  Nursery ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,195",
    "Year Built": 1929,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.12,
    "Original List Price": "$124,900",
    "List Price": "$124,900",
    "Sale Price": "$122,000",
    "SPLP": "97.7%",
    "SP Sq Ft": "$102.09",
    "Contract Date": "10/4/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "221  Merriman ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,574",
    "Year Built": 1900,
    "Total Rooms": 9,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.09,
    "Original List Price": "$174,900",
    "List Price": "$149,900",
    "Sale Price": "$130,500",
    "SPLP": "87.1%",
    "SP Sq Ft": "$82.91",
    "Contract Date": "10/5/2016",
    "DOM": 54
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "53  Lansdale ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,450",
    "Year Built": 1930,
    "Total Rooms": 8,
    "Beds Total": 4,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.09,
    "Original List Price": "$134,900",
    "List Price": "$134,900",
    "Sale Price": "$125,000",
    "SPLP": "92.7%",
    "SP Sq Ft": "$86.21",
    "Contract Date": "10/13/2016",
    "DOM": 54
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "242  Cypress ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,650",
    "Year Built": 1880,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.09,
    "Original List Price": "$139,000",
    "List Price": "$139,000",
    "Sale Price": "$132,000",
    "SPLP": "95.0%",
    "SP Sq Ft": "$80.00",
    "Contract Date": "10/16/2016",
    "DOM": 40
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "43  Weider ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,586",
    "Year Built": 1890,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.12,
    "Original List Price": "$120,000",
    "List Price": "$120,000",
    "Sale Price": "$125,000",
    "SPLP": "104.2%",
    "SP Sq Ft": "$78.81",
    "Contract Date": "10/23/2016",
    "DOM": 13
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "175  Crawford ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,525",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 4,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.09,
    "Original List Price": "$144,900",
    "List Price": "$134,900",
    "Sale Price": "$134,000",
    "SPLP": "99.3%",
    "SP Sq Ft": "$87.87",
    "Contract Date": "10/25/2016",
    "DOM": 65
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "101  Westview TER",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": 900,
    "Year Built": 1935,
    "Total Rooms": 5,
    "Beds Total": 2,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.09,
    "Original List Price": "$109,900",
    "List Price": "$109,900",
    "Sale Price": "$112,000",
    "SPLP": "101.9%",
    "SP Sq Ft": "$124.44",
    "Contract Date": "10/26/2016",
    "DOM": 3
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "431  Caroline RD",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Cape Cod",
    "Sq Ft Total": "1,640",
    "Year Built": 1900,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$124,900",
    "List Price": "$124,900",
    "Sale Price": "$124,000",
    "SPLP": "99.3%",
    "SP Sq Ft": "$75.61",
    "Contract Date": "10/29/2016",
    "DOM": 7
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "48  Cornell ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story",
    "Sq Ft Total": "2,526",
    "Year Built": 1900,
    "Total Rooms": 12,
    "Beds Total": 5,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.11,
    "Original List Price": "$137,000",
    "List Price": "$137,000",
    "Sale Price": "$137,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$54.24",
    "Contract Date": "11/1/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "7  Pembroke ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,188",
    "Year Built": 1908,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.07,
    "Original List Price": "$115,000",
    "List Price": "$115,000",
    "Sale Price": "$115,000",
    "SPLP": "100.0%",
    "SP Sq Ft": "$96.80",
    "Contract Date": "11/2/2016",
    "DOM": 14
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "66  Lansdale ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,432",
    "Year Built": 1910,
    "Total Rooms": 7,
    "Beds Total": 4,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$129,900",
    "List Price": "$129,900",
    "Sale Price": "$135,000",
    "SPLP": "103.9%",
    "SP Sq Ft": "$94.27",
    "Contract Date": "11/3/2016",
    "DOM": 10
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "635  Linden ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,390",
    "Year Built": 1900,
    "Total Rooms": 6,
    "Beds Total": 3,
    "Baths Total": 2,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.08,
    "Original List Price": "$118,000",
    "List Price": "$95,000",
    "Sale Price": "$90,000",
    "SPLP": "94.7%",
    "SP Sq Ft": "$64.75",
    "Contract Date": "11/6/2016",
    "DOM": 138
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "518  Caroline ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Bungalow, Ranch",
    "Sq Ft Total": 710,
    "Year Built": 1924,
    "Total Rooms": 4,
    "Beds Total": 2,
    "Baths Total": 1,
    "Numof Garage Spaces": 0,
    "Numof Acres": 0.06,
    "Original List Price": "$39,900",
    "List Price": "$39,900",
    "Sale Price": "$36,000",
    "SPLP": "90.2%",
    "SP Sq Ft": "$50.70",
    "Contract Date": "11/14/2016",
    "DOM": 0
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "105  Raleigh ST",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Ranch",
    "Sq Ft Total": "1,010",
    "Year Built": 1959,
    "Total Rooms": 4,
    "Beds Total": 2,
    "Baths Total": 1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.09,
    "Original List Price": "$124,900",
    "List Price": "$124,900",
    "Sale Price": "$122,000",
    "SPLP": "97.7%",
    "SP Sq Ft": "$120.79",
    "Contract Date": "11/25/2016",
    "DOM": 4
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "1283  Park AVE",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "2 Story, Colonial",
    "Sq Ft Total": "1,375",
    "Year Built": 1920,
    "Total Rooms": 7,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 2,
    "Numof Acres": 0.13,
    "Original List Price": "$119,900",
    "List Price": "$119,900",
    "Sale Price": "$120,000",
    "SPLP": "100.1%",
    "SP Sq Ft": "$87.27",
    "Contract Date": "12/1/2016",
    "DOM": 1
  },
  {
    "Type": "RES",
    "St": "S",
    "Address": "396  Hillside AVE",
    "Town/City": "Rochester",
    "School District Name": "Rochester",
    "Styles Of Residence": "Colonial",
    "Sq Ft Total": "1,432",
    "Year Built": 1950,
    "Total Rooms": 5,
    "Beds Total": 3,
    "Baths Total": 1.1,
    "Numof Garage Spaces": 1,
    "Numof Acres": 0.13,
    "Original List Price": "$100,000",
    "List Price": "$100,000",
    "Sale Price": "$120,000",
    "SPLP": "120.0%",
    "SP Sq Ft": "$83.80",
    "Contract Date": "12/10/2016",
    "DOM": 14
  }
]